--1. LIST THE FOLLOWING DETAILS OF EACH EMPLOYEE: EMPLOYEE NUMBER, LAST NAME, FIRST NAME, SEX AND SALARY
SELECT EMPLOYEES.EMP_NO, LAST_NAME, FIRST_NAME, SEX, SALARIES.SALARY
FROM EMPLOYEES
INNER JOIN SALARIES ON
EMPLOYEES.EMP_NO = SALARIES.EMP_NO;

--2.LIST FIRST NAME, LAST NAME AND HIRE DATE FOR EMPLOYEES WHO WERE HIRED IN 1986
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE
FROM EMPLOYEES
where  DATEPART(year, [HIRE_DATE]) = cast(@year as int)
       and datepart(YEAR, [HIRE_DATE]) = '1986';
	   
--3.  LIST THE MANAGER OF EACH DEPARTMENT WITH THE FOLLOWING INFORMATION: DEPARTMENT NUMBER, DEPARTMENT NAME, THE MANAGERS EMPLOYEE NUMBER, LAST NAME, FIRST NAME
SELECT DEPARTMENTS.DEPT_NO, DEPARTMENTS.DEPT_NAME, DEPT_MANAGER.EMP_NO, EMPLOYEES.LAST_NAME, EMPLOYEES.FIRST_NAME
FROM DEPARTMENTS
INNER JOIN DEPT_MANAGER ON
	DEPARTMENTS.DEPT_NO = DEPT_MANAGER.DEPT_NO
	INNER JOIN EMPLOYEES ON
	DEPT_MANAGER.EMP_NO = EMPLOYEES.EMP_NO;
	
--4. LIST THE DEPARTMENT OF EACH EMPLOYEE WITH THE FOLLOWING INFO9RMATION: EMPLOYEE NUMBR, LAST NAME, FIRST NAME AND DEPARTMENT NAME	
SELECT EMPLOYEES.EMP_NO, EMPLOYEES.LAST_NAME, EMPLOYEES.FIRST_NAME, DEPARTMENTS.DEPT_NAME
FROM EMPLOYEES
INNER JOIN DEPT_EMP ON
	EMPLOYEES.EMP_NO = DEPT_EMP.EMP_NO
	INNER JOIN DEPARTMENTS ON
	DEPT_EMP.DEPT_NO = DEPARTMENTS.DEPT_NO;
	
--5. LIST FIRST NAME, LAST NAME AND SEX FOR EMPLOYEES WHOSE FIRST NAME IS HERCULES AND LAST NAME BEGINS WITH B	
SELECT FIRST_NAME, LAST_NAME, SEX
FROM EMPLOYEES
WHERE FIRST_NAME = 'Hercules' 
	AND LAST_NAME LIKE 'B%';
	
--6.  LIST ALL EMPLOYEES IN THE SALES DEPARTMENT, INCLUDING THEIR EMPLOYEE NUMBER, LAST NAME, FIRST NAME AND DEPARTMENT NAME	
SELECT EMPLOYEES.EMP_NO, EMPLOYEES.LAST_NAME, EMPLOYEES.FIRST_NAME, DEPARTMENTS.DEPT_NAME
FROM EMPLOYEES
INNER JOIN DEPT_EMP ON
	EMPLOYEES.EMP_NO = DEPT_EMP.EMP_NO
	INNER JOIN DEPARTMENTS ON
	DEPT_EMP.DEPT_NO = DEPARTMENTS.DEPT_NO
	WHERE DEPT_NAME = 'Sales';
	
--7. LIST ALL EMPLOYEES IN THE SALES AND DEVELOPMENT DEPARTMENTS, INCLUDING THEIR EMPLOYEE NUMBER, LAST NAME, FIRST NAME AND DPEARTMENT NAME.
SELECT EMPLOYEES.EMP_NO, EMPLOYEES.LAST_NAME, EMPLOYEES.FIRST_NAME, DEPARTMENTS.DEPT_NAME
FROM EMPLOYEES
INNER JOIN DEPT_EMP ON
	EMPLOYEES.EMP_NO = DEPT_EMP.EMP_NO
	INNER JOIN DEPARTMENTS ON
	DEPT_EMP.DEPT_NO = DEPARTMENTS.DEPT_NO
	WHERE DEPT_NAME = 'Sales'
		OR DEPT_NAME = 'Development';
		
--8.  IN DESCENDING ORDER, LIST THE FREQUENCY COUNT OF EMPLOYEE LAST NAMES, I.E. HOW MANY EMPLOYEES SHARE EACH LAST NAME
SELECT LAST_NAME, COUNT(LAST_NAME) AS "NAME COUNT"
FROM EMPLOYEES
GROUP BY LAST_NAME
ORDER BY "NAME COUNT" DESC;

	