DROP TABLE DEPT_MANAGER

CREATE TABLE TITLES (
	TITLE_ID VARCHAR(5) NOT NULL PRIMARY KEY,
	TITLE VARCHAR(30) NOT NULL);

ALTER TABLE TITLES
RENAME COLUMN TITLE_ID TO EMP_TITLE_ID;
	
SELECT * FROM TITLES; 

CREATE TABLE EMPLOYEES (
	EMP_NO INT NOT NULL PRIMARY KEY,
	EMP_TITLE_ID VARCHAR(30) NOT NULL REFERENCES TITLES(EMP_TITLE_ID),
	BIRTH_DATE date NOT NULL,
	FIRST_NAME VARCHAR(30) NOT NULL, 
	LAST_NAME VARCHAR(30) NOT NULL,
	SEX VARCHAR(1) NOT NULL, 
	HIRE_DATE date NOT NULL);

SELECT * FROM EMPLOYEES;

CREATE TABLE DEPARTMENTS (
	DEPT_NO VARCHAR(4) NOT NULL PRIMARY KEY,
	DEPT_NAME VARCHAR(30) NOT NULL);

SELECT * FROM DEPARTMENTS;

CREATE TABLE DEPT_MANAGER (
	DEPT_NO VARCHAR(4) NOT NULL REFERENCES DEPARTMENTS(DEPT_NO),
	EMP_NO INT NOT NULL REFERENCES EMPLOYEES(EMP_NO));

SELECT * FROM DEPT_MANAGER;

CREATE TABLE DEPT_EMP (
	EMP_NO INT NOT NULL REFERENCES EMPLOYEES(EMP_NO),
	DEPT_NO VARCHAR(4) NOT NULL REFERENCES DEPARTMENTS(DEPT_NO));
	
SELECT * FROM DEPT_EMP;

CREATE TABLE SALARIES (
	EMP_NO INT NOT NULL REFERENCES EMPLOYEES(EMP_NO),
	SALARY INT NOT NULL);
	
SELECT * FROM SALARIES;



